    version: '3'
    services:
      nginx:
        image: nginx:latest
        ports:
          - "8000:80"
        volumes:
          - ./hosts:/etc/nginx/conf.d
          - ./var/www/192.168.0.94/:/var/www/192.168.0.94
          - /var/logs:/var/log/nginx
        links:
          - php
      php:
        build: ./php
        volumes:
          - ./var/www/192.168.0.94/:/var/www/192.168.0.94